### PR TITLE
add handler for /store/coupon/<id>/edit POST

### LINKED ISSUE #77: store handlers for viewing, creating, and editing coupons
I'll do this.

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR adds a handler for `/store/coupon/<id>/edit` POST.  All of the routes specified in #77 have been added, so this closes #77.

Also, the last four commits (b6bbe63, 5dcb41d, 22a7c5b, and 240edd2) add a `Kucipong.Handler.Route` module, which holds all of the full routes for the app.  This should make implementing #84 easier.

### CODE REVIEW

**Review by arowM — COMMENTED** [review]
@cdepillabout 
Basically looks good.
It might be the independent issue for this PR, but it seems on coupon edit page, clicking submit button does not fire any effects.
Do you have any idea why?

**Comment by cdepillabout** [comment]
@arowM Thanks for the review.

What sort of effects are you talking about?  Maybe you're talking about javascript events?

In `frontend/src/pug/storeUser_store_coupon_id_edit.pug`, there doesn't appear to be any sort of `onClick` events or anything like that.

```pug
.couponSubmit
  button.btn.outerBtn(type="submit")
    | この内容で店舗情報を更新する
```

I also searched the code for something referring to the `couponSubmit` class, but I couldn't find anything.

**Comment by arowM** [comment]
@cdepillabout 
> What sort of effects are you talking about?

I just meant that no data seems to be sent to server even if I clicked submit button.
Because the `type` attribute of the submit button is `submit` and parent `form` tag has `action` attribute, the input data should be sent to the URL specified by the `action` attribute, I guess.

I'll check the reason of the unexpected behavior, too.

**Comment by cdepillabout** [comment]
Hmm, that's strange.  If I go to a URL like http://localhost:8101/store/coupon/14/edit and press "この内容で店舗情報を更新する", the form is submitted.  I've tested with both Firefox and Chromium.

**Comment by arowM** [comment]
@cdepillabout 
I've tried again, and it works now.
I might have built executable in wrong way.
If I reproduce the bug again, then I'll create a new issue.

**Pull request merged**
