### PR TITLE
I18n for store pages

### LINKED ISSUE #62: i18n
Kucipong is a service for Indonesia.
To serve Indonesian message, all hard coded messages should be managed in a single file.

### PR DESCRIPTION
**Pull request by arowM**
This PR closes #62.
Make sure that this PR depends on #69 .
Main changes are on 35e12cb.
Commits on ad335ca makes messages more user friendly.

@cdepillabout , please review.

### CODE REVIEW

**Comment by cdepillabout** [comment]
Looks good to me.  Thanks for reformatting with hindent.

**Comment by cdepillabout** [comment]
When I merged this in, I clicked "rebase and merge" instead of just doing a normal merge.  
I was hoping it would rebase this branch on top of `master`, and then create a merge commit like normal.  It looks like no merge commit was created.  

If I want that sort of functionality, I guess I'll have to do a rebase manually, then use github to create the merge commit.

**Comment by arowM** [comment]
I use this sort of functionality if the commits are enough simple to push directly to `master`.
(I use "rebase and merge" on all PRs of my own repositories in my responsibility).
I prefer this functionality only by the reason that it makes commit logs more simple like if we simply push to `master`.

**Comment by cdepillabout** [comment]
I also commit directly to master when I am working on a project by myself.

I think using rebase-and-then-merge-commit makes the history easier to understand when working with multiple people.  The history for kucipong (this repository) is pretty easy to read when viewed in something like `git log --graph` or `gitk`.

**Comment by arowM** [comment]
@cdepillabout 
So, do you propose to obey following policy for merging on kucipong (this repository)?

* Directly push to `master` if the commits are about trivial changes
* Use normal "merge" for all PRs

**Comment by cdepillabout** [comment]
@arowM That sounds good to me!

**Pull request merged**
