### PR TITLE
This adds the /store GET, /store/edit GET, and /store/edit POST handlers

### PR DESCRIPTION
**Pull request by cdepillabout**
@arowM I edited `frontend/src/pug/storeUser_store.pug` and `frontend/src/pug/storeUser_store_edit.pug` to make use of the values I was passing in.  Can you take a look at it and let me know what you think?

### CODE REVIEW

**Comment by cdepillabout** [comment]
This PR doesn't deal with `BusinessCategoryDetail` or the `Image` fields of `Store`.  Those are left for issues #54 and #55.

**Comment by cdepillabout** [comment]
Closes #52.

**Comment by arowM** [comment]
@cdepillabout 

It seems the changes for the `frontend/src/pug/*.pug` is following two types, broadly dividing them.

a. Change `name` for current API request specification
b. Replace sample texts with template variables

About `a`: Could you update `doc/api.md`?
About `b`:
If we make the type of `businessCategoryDetail` to be `[String]` (or something like that), we can use `for` statement like this.

```
.storeBody_info_body_row-body.simpleTagWrapper
  | {% for businessCategoryDetail in businessCategoryDetails %}
  .simpleTag
    | {{ businessCategoryDetail }}
  | {% endfor %}
```

The `businessHours` may also be better to write like this.

```
.storeBody_info_body_row-body
  | {% for businessHourLine in businessHourLines %}
  p
    | {{ businessHourLine }}
  | {% endfor %}
```

(where `businessHourLines = lines businessHours`)

**Comment by cdepillabout** [comment]
@arowM Thanks for the review.  I've fixed the problems you've pointed out.

For (a), I've updated the API specification in commit 877dc35.  For (b), I've updated businessHours to be output as multiple strings, using `lines`.

I've also changed `businessCategoryDetail` to be a `[Text]`, but I think it might not be sufficient.

Unless you have any objections, I'll merge in this PR, and then fix `businessCategoryDetail` in a separate PR (and in issue #54).

**Comment by cdepillabout** [comment]
Oh yeah, this PR is also not handling images.  That will be done in #55.

**Pull request merged**
